// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMz5BJ4CEgLYauOSeAwvrjfzcb4XuEuds',
    appId: '1:558685601928:web:b3cde839cc78d0d20b5f3d',
    messagingSenderId: '558685601928',
    projectId: 'pocket-flow-a2819',
    authDomain: 'pocket-flow-a2819.firebaseapp.com',
    storageBucket: 'pocket-flow-a2819.firebasestorage.app',
    measurementId: 'G-BENFDGE7PN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2X3Bk5jIKDFuTjZSCBbJxIg-srboAG7g',
    appId: '1:558685601928:android:c829fafb81a2379b0b5f3d',
    messagingSenderId: '558685601928',
    projectId: 'pocket-flow-a2819',
    storageBucket: 'pocket-flow-a2819.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDovkQ2qDYmcvMP-5ZgSXzNti5Fd4qt8U',
    appId: '1:558685601928:ios:810a1ac36a9a89f40b5f3d',
    messagingSenderId: '558685601928',
    projectId: 'pocket-flow-a2819',
    storageBucket: 'pocket-flow-a2819.firebasestorage.app',
    androidClientId: '558685601928-7qntpbogcdjjb59h1iams0uru5qdgvor.apps.googleusercontent.com',
    iosClientId: '558685601928-ipbk3uu80nbde8emmr1shena0s9c9fem.apps.googleusercontent.com',
    iosBundleId: 'com.example.pocketflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDovkQ2qDYmcvMP-5ZgSXzNti5Fd4qt8U',
    appId: '1:558685601928:ios:810a1ac36a9a89f40b5f3d',
    messagingSenderId: '558685601928',
    projectId: 'pocket-flow-a2819',
    storageBucket: 'pocket-flow-a2819.firebasestorage.app',
    androidClientId: '558685601928-7qntpbogcdjjb59h1iams0uru5qdgvor.apps.googleusercontent.com',
    iosClientId: '558685601928-ipbk3uu80nbde8emmr1shena0s9c9fem.apps.googleusercontent.com',
    iosBundleId: 'com.example.pocketflow',
  );

}